Update xenoseq_prep

diff --git a/bin/xenoseq_prep b/bin/xenoseq_prep
--- a/bin/xenoseq_prep
+++ b/bin/xenoseq_prep
@@ -37,8 +37,8 @@ while [ $# -gt 0 ]; do
 		cores=("$2")
 	elif [[ $1 =~ ^(-a|--assembler)$ ]]; then
 		assembler=("$2")
-	elif [[ $1 =~ ^(-T|--assembler)$ ]]; then
-		assembler=("$2")
+	elif [[ $1 =~ ^(-T|--assembler_tmp)$ ]]; then
+		assembler_tmp=("$2")
 	elif [[ $1 == *"-"* ]]; then	 # Capture any other flag in variable just in case
 		v="${1/-/}"
 		declare $v="$2"
@@ -51,6 +51,7 @@ mkdir -p $output/logs
 mkdir -p $output/reads
 mkdir -p $output/read_mapping
 mkdir -p $output/reads/QCreports
+mkdir -p $assembler_tmp
 filename=$(basename -- "$output")
 filename="${filename%.*}"
 
@@ -71,10 +72,18 @@ fi
 if [ -f $output/assembly/final.contigs.fa ]; then
 	echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] ${ORANGE}NOTE: using pre-existing $output/assembly/final.contigs.fa ${NC}"
 else
-	echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Using megahit to assemble reads"
-	megahit -r $output/reads/prepped_reads.fastq -t $cores --min-contig-len 75 --preset meta-large -o $output/assembly &> $output/logs/megahit.log
-	success $? "Megahit"
-	echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Assembly completed; ${BLUE} $output/assembly/final.contigs.fa ${NC}"
+        if [[ "$assembler" == "megahit" ]]; then
+	        echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Using megahit to assemble reads"
+	        megahit -r $output/reads/prepped_reads.fastq -t $cores --min-contig-len 75 --preset meta-large -o $output/assembly &> $output/logs/megahit.log
+	        success $? "Megahit"
+	        echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Assembly completed; ${BLUE} $output/assembly/final.contigs.fa ${NC}"
+        else if [[ "$asembler" == "penguin" ]]; then
+	        echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Using penguin to assemble reads"
+	        penguin $output/reads/prepped_reads.fastq -t $cores --min-contig-len 75 --preset meta-large -o $output/assembly &> $output/logs/megahit.log
+	        success $? "Penguin"
+	        echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Assembly completed; ${BLUE} $output/assembly/final.contigs.fa ${NC}"
+        else
+                echo -e "[xenoseq_prep     $(date +%d-%m_%H:%M:%S)] Assembly failed;"
 fi
 
 
